/*
mmrnames.inc

verilog includes file mapping mmr names to addresses.
*/

localparam VGASWFB	= 8'h0;
localparam RANDNUM	= 8'h4;
localparam LEDS 		= 8'h5;
localparam S0RCV		= 8'h6;
localparam S0SND		= 8'h8;
localparam TMRCNT	= 8'hA;
localparam TMRDIV	= 8'hC;

localparam IRQSTA	= 8'hF;
localparam IRQEN		= 8'h10;
localparam EXP		= 8'h11;

localparam KBD		= 8'h12;
localparam MOUSE		= 8'h14;
localparam DIPS		= 8'h16;
localparam PBS		= 8'h17;

localparam ARRWID	= 8'h18;
localparam IRQDIS	= 8'h1A;

//parameter 	= 8'h;
